version: '3.4'

networks:
  weatherio-net:

services:
  weatherio-server:
    container_name: weatherio-server
    image: weatherioserver
    build:
      context: .
      dockerfile: WeatherIO.Server/Dockerfile
      args:
        PASSWORD: ${CERT_PASSWD}
    ports:
      - 443:443
    depends_on:
      - weatherio-db
    environment:
      - DB_HOST=weatherio-db
      - DB_NAME=WeatherIO
      - DB_SA_PASSWORD=${DB_PASSWD}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/WeatherIO.Server.pfx
    networks:
      - weatherio-net
  weatherio-db:
    container_name: weatherio-db
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWD}
    networks:
      - weatherio-net
  weatherio-web:
    container_name: weatherio-web
    image: weatherioweb
    build:
      context: .
      dockerfile: WeatherIO.Web/Dockerfile
    ports:
      - 80:80
    networks:
      - weatherio-net
