version: '3.4'

networks:
  weatherio-net:

services:
  weatherio.server:
    container_name: weatherio.server
    image: ${DOCKER_REGISTRY-}weatherioserver
    build:
      context: .
      dockerfile: WeatherIO.Server/Dockerfile
      args:
        PASSWORD: ${CERT_PASSWD}
    ports:
     - 8001:443
     - 8002:80
    depends_on:
     - weatherio-db
    environment:
     - DB_HOST=weatherio-db
     - DB_NAME=WeatherIO
     - DB_SA_PASSWORD=${DB_PASSWD}
    networks:
     - weatherio-net
  weatherio-db:
    container_name: weatherio-db
    image: mcr.microsoft.com/azure-sql-edge
    ports:
     - 8003:1433
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=${DB_PASSWD}
    networks:
     - weatherio-net
